[package]
name = "rust-http-server"
version = "1.0.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
flate2 = "1.0"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
glob = "0.3.0"
mime_guess = "2.0.4"
